import react from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import Layout from "../components/Layout";
import { useTheme } from "next-themes";
import Image from "next/image";

export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Ahmad Nagm</title>
        <meta name="description" content="Generated by create next app" />
        <meta charset="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.s1}>
        <div className={styles.mainContainer}>
          <h1>Hi, I'm Ahmad Nagm</h1>
          <div className={styles.wrapper}>
            <div className={styles.mac}>
              <div className={styles.macWrap}>
                <div className={styles.dotOne}></div>
                <div className={styles.dotTwo}></div>
                <div className={styles.dotThree}></div>
              </div>
            </div>
            <div className={styles.leftColumn}>
              <div className={styles.profilePic}>
                <Image
                  src="/../public/negm.jpg"
                  alt="person"
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <h5>Themes</h5>
              <div className={styles.themeSettings}>
                <div
                  className={styles.light}
                  onClick={() => setTheme(theme === "dark" ? "light" : "light")}
                ></div>
                <div
                  className={styles.blue}
                  onClick={() => setTheme(theme === "dark" ? "dark" : "dark")}
                ></div>
                <div
                  className={styles.green}
                  onClick={() => setTheme(theme === "dark" ? "green" : "green")}
                ></div>
                <div
                  className={styles.purple}
                  onClick={() =>
                    setTheme(theme === "dark" ? "purple" : "purple")
                  }
                ></div>
              </div>
              <p>Theme Settings will be save for your next visit</p>
            </div>
            <div className={styles.rightColumn}>
              <div className={styles.contentShadow}>
                <div className={styles.content}>
                  <div className={styles.cornerOne}></div>
                  <div className={styles.cornerTwo}></div>
                  <div className={styles.cornerThree}></div>
                  <div className={styles.cornerFour}></div>
                  <h3>What I do</h3>
                  <p>
                    I am a Front-End Developer With 2 Years Of Professional
                    Experience, I love to build websites from scratch.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.s2}>
        <div className={styles.mainContainer}>
          <div className={styles.aboutWrapper}>
            <div className={styles.aboutMe}>
              <h4>About Me</h4>
              <p>I build new projects just to tickle my brain</p>
              <hr />
              <h4>TOP EXPERTICE </h4>
              <p>
                Front-end developer with 2 years of Professional Experience |
                <a href="#" target="_blank">
                  Download Resume
                </a>
              </p>
              <div className={styles.skills}>
                <ul>
                  <li>HTML5</li>
                  <li>CSS3</li>
                  <li>JavaScript</li>
                  <li>Jquery</li>
                </ul>
                <ul>
                  <li>Bootstrap5</li>
                  <li>Sass</li>
                  <li>AdobeXD</li>
                  <li>Figma</li>
                </ul>
              </div>
            </div>

            <div className={styles.social}>
              <div className={styles.socialPic}>
                <Image
                  src="/../public/pexels-pixabay-273238.jpg"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <h3>Find Me On</h3>
              <div className={styles.socialLinks}>
                <a href="#">Facebook</a>
                <p>|</p>
                <a href="#">twitter</a>
                <p>|</p>
                <a href="#">instagram</a>
                <p>|</p>
                <a href="#">linkedin</a>
                <p>|</p>
                <a href="#">behance</a>
                <p>|</p>
                <a href="#">Youtube</a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.s1}>
        <div className={styles.mainContainer}>
          <h1 className={styles.cardsTopic}>Some Of My Past Projects</h1>
          <div className={styles.cards}>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/../public/pexels-pixabay-273238.jpg"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>The Title Of The Post</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint
                  ipsa nobis sunt, quibusdam
                </p>
                <Link href="/">Read more</Link>
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/../public/pexels-pixabay-273238.jpg"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>The Title Of The Post</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint
                  ipsa nobis sunt, quibusdam
                </p>
                <Link href="/">Read more</Link>
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/../public/pexels-pixabay-273238.jpg"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>The Title Of The Post</h4>
                <p>
                  Lorem ipsum dolor sit amet consectetur adipisicing elit. Sint
                  ipsa nobis sunt, quibusdam
                </p>
                <Link href="/">Read more</Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
