import react from "react";
import Head from "next/head";
import Link from "next/link";
import styles from "../styles/Home.module.scss";
import Layout from "../Layout/Layout";
import { useTheme } from "next-themes";
import Image from "next/image";
import { library } from "@fortawesome/fontawesome-svg-core";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faHome,
  faCode,
  fasLabtopCode,
  faLaptopCode,
  faBlog,
  faPen,
  faEnvelope,
  faAngleDoubleDown,
  faScrewdriver,
  faPaintBrush,
} from "@fortawesome/free-solid-svg-icons";
import {
  faBehance,
  faBootstrap,
  faContao,
  faCss3,
  faFacebook,
  faFacebookMessenger,
  faFigma,
  faHtml5,
  faInstagram,
  faJs,
  faJsSquare,
  faLinkedin,
  faSass,
  faTwitter,
  faWpforms,
  faYoutube,
} from "@fortawesome/free-brands-svg-icons";
export default function Home() {
  const { theme, setTheme } = useTheme();
  return (
    <>
      <Head>
        <title>Ahmad Nagm</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <link
          rel="apple-touch-icon"
          sizes="180x180"
          href="/apple-touch-icon.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="32x32"
          href="/favicon-32x32.png"
        />
        <link
          rel="icon"
          type="image/png"
          sizes="16x16"
          href="/favicon-16x16.png"
        />
        <link rel="manifest" href="/site.webmanifest" />
      </Head>

      <div className={styles.s1}>
        <div className={styles.mainContainer}>
          <h1>Hi, I&apos;m Ahmad Nagm</h1>
          <div className={styles.wrapper}>
            <div className={styles.mac}>
              <div className={styles.macWrap}>
                <div className={styles.dotOne}></div>
                <div className={styles.dotTwo}></div>
                <div className={styles.dotThree}></div>
              </div>
            </div>
            <div className={styles.leftColumn}>
              <div className={styles.profilePic}>
                <Image
                  src="/negm.jpg"
                  alt="person"
                  height={400}
                  width={600}
                  layout="responsive"
                />
              </div>
              <h5>Themes</h5>
              <div className={styles.themeSettings}>
                <div
                  className={styles.light}
                  onClick={() => setTheme(theme === "dark" ? "light" : "light")}
                ></div>
                <div
                  className={styles.blue}
                  onClick={() => setTheme(theme === "dark" ? "dark" : "dark")}
                ></div>
                <div
                  className={styles.green}
                  onClick={() => setTheme(theme === "dark" ? "green" : "green")}
                ></div>
                <div
                  className={styles.purple}
                  onClick={() =>
                    setTheme(theme === "dark" ? "purple" : "purple")
                  }
                ></div>
              </div>
              <p>Theme Settings will be save for your next visit</p>
            </div>
            <div className={styles.rightColumn}>
              <div className={styles.contentShadow}>
                <div className={styles.content}>
                  <div className={styles.cornerOne}></div>
                  <div className={styles.cornerTwo}></div>
                  <div className={styles.cornerThree}></div>
                  <div className={styles.cornerFour}></div>
                  <h3>What I do</h3>
                  <p>
                    I am a Front-End Developer With 2 Years Of Professional
                    Experience, I love to build websites from scratch.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.s2}>
        <div className={styles.mainContainer}>
          <div className={styles.aboutWrapper}>
            <div className={styles.aboutMe}>
              <h4>ABOUT ME</h4>
              <p>I build new projects just to tickle my brain</p>
              <hr />
              <h4>TOP EXPERTICE </h4>
              <p>
                Front-end developer with 2 years of Professional Experience |
                <a href="#" target="_blank">
                  Download Resume
                </a>
              </p>
              <div className={styles.skills}>
                <ul>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faHtml5} />
                    </span>
                    HTML5
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faCss3} />
                    </span>
                    CSS3
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faJs} />
                    </span>
                    JavaScript
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faJsSquare} />
                    </span>
                    Jquery
                  </li>
                </ul>
                <ul>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faBootstrap} />
                    </span>
                    Bootstrap5
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faSass} />
                    </span>
                    Sass
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faPaintBrush} />
                    </span>
                    AdobeXD
                  </li>
                  <li>
                    <span>
                      <FontAwesomeIcon icon={faFigma} />
                    </span>
                    Figma
                  </li>
                </ul>
              </div>
            </div>

            <div className={styles.social}>
              <div className={styles.socialPic}>
                <Image
                  src="/nubelson-fernandes--Xqckh_XVU4-unsplash.jpg"
                  alt="person"
                  height={400}
                  width={600}
                  layout="responsive"
                />
              </div>
              <h3>Find Me On</h3>
              <div className={styles.socialLinks}>
                <a href="https://www.facebook.com/ahmad.magdy.129/">
                  <h4>
                    <FontAwesomeIcon icon={faFacebook} />
                  </h4>
                </a>

                <a href="https://www.instagram.com/ahmed_magdy_negm/">
                  <h4>
                    <FontAwesomeIcon icon={faInstagram} />
                  </h4>
                </a>

                <a href="https://twitter.com/DevAhmdNagm">
                  <h4>
                    <FontAwesomeIcon icon={faTwitter} />
                  </h4>
                </a>

                <a href="https://www.linkedin.com/in/ahmad-negm/">
                  <h4>
                    <FontAwesomeIcon icon={faLinkedin} />
                  </h4>
                </a>

                <a href="https://www.behance.net/ahmadnegm2000">
                  <h4>
                    <FontAwesomeIcon icon={faBehance} />
                  </h4>
                </a>

                <a href="https://www.youtube.com/channel/UCGjOEhwmaJsha-cVvLVTXbA">
                  <h4>
                    <FontAwesomeIcon icon={faYoutube} />
                  </h4>
                </a>
              </div>
            </div>
          </div>
        </div>
      </div>
      <div className={styles.s1}>
        <div className={styles.mainContainer}>
          <h1 className={styles.cardsTopic}>Some Of My Past Projects</h1>
          <div className={styles.cards}>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/3.png"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>Chat Website</h4>
                <p>Awesome Simple Design for chat website....</p>
                <Link href="/work/1">Read more</Link>
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/1.png"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>Game Website Layout</h4>
                <p>Game website design with dark colors...</p>
                <Link href="/work/1">Read more</Link>
              </div>
            </div>
            <div className={styles.card}>
              <div className={styles.cardImg}>
                <Image
                  src="/2.png"
                  className={styles.image}
                  height={400}
                  width={600}
                  alt="person"
                  layout="responsive"
                />
              </div>
              <div className={styles.cardBody}>
                <h4>Landing Page</h4>
                <p>Awesome Landing Page Design for a Company website...</p>
                <Link href="/work/1">Read more</Link>
              </div>
            </div>
          </div>
        </div>
      </div>
    </>
  );
}
